### ISSUE TITLE
With wdio 4.8, met Error: reporter "wdio-spec-reporter" is not installed.

### ISSUE THREAD

**Issue by kchjxxgh** [webdriverio/wdio-spec-reporter#44]
With latest webdriverio 4.8, i got this error when try to use "spec" reporter.

C:\Users\kchen\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:158
                        throw _iteratorError;
                        ^

Error: reporter "wdio-spec-reporter" is not installed. Error: Error: Cannot find module 'wdio-spec-reporter'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Launcher.initReporters (C:\Users\kchen\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:133:40)
    at new Launcher (C:\Users\kchen\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:69:31)
    at Object.<anonymous> (C:\Users\kchen\AppData\Roaming\npm\node_modules\webdriverio\build\lib\cli.js:424:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at Launcher.initReporters (C:\Users\kchen\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:135:35)
    at new Launcher (C:\Users\kchen\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:69:31)
    at Object.<anonymous> (C:\Users\kchen\AppData\Roaming\npm\node_modules\webdriverio\build\lib\cli.js:424:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by christian-bromann** [comment]
> Error: reporter "wdio-spec-reporter" is not installed. Error: Error: Cannot find module 'wdio-spec-reporter'

It seems it can't find the reporter in your node_modules. Make sure you have it installed on the same level (global or local). Also please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by kchjxxgh** [comment]
But I did installed this module, and i also tried some other reporter, only dot reporter can work well. 
I also check the node_modules folder, the wdio-spec-reporter, wdio-json-reporter and so on,  was installed on the same level as wdio-dot-reporter.

**Comment by christian-bromann** [comment]
Do you have `webdriverio` installed on that same level too?

**Comment by acailly** [comment]
I have the same issue (on windows 10).
I downloaded the webdriverio cucumber-boilerplate (https://github.com/webdriverio/cucumber-boilerplate) and installed with 'npm install'.
Then I installed webdriverio globally to have the `wdio` command accessible from anywhere.
Finally, typing `wdio` in the project folder resulted in the same error: `"wdio-spec-reporter" is not installed`

To make it work, I simply:
- uninstalled the global webdriverio (npm uninstall -g webdriverio)
- added a script in package.json: `"wdio": "wdio"`
- ran the script `npm run wdio` instead of just typing `wdio`

Still wonder how it is supposed to work when using a globally installed webdriverio...

**Comment by christian-bromann** [comment]
If you install webdriverio globally , you need to install the spec reporter globally too

**Comment by juuxstar** [comment]
Getting the same issue. 

Looks like in `package.json` the `main` property specifies `build/reporter.js` but no such dir/file is present in the npm package.

Does this project need to be built before publishing to npm?

**Comment by christian-bromann** [comment]
@juuxstar no, I have no issues when I download the latest spec reporter
